/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    id("net.minecrell.plugin-yml.bukkit") version "0.5.1"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    compileOnly("org.spigotmc:spigot-api:1.18-R0.1-SNAPSHOT")
}

group = "net.maploop"
version = "1.10.1"
description = "GrapplingHook"
java.sourceCompatibility = JavaVersion.VERSION_16


publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }

    /*tasks {
        jar {
            destinationDirectory.set(file("D:/stuff/Code/debug-server/plugins")) // Ignore please, I use this for debugging.
        }
    }*/
}

bukkit {
    main = "net.maploop.GrapplingHook"
    apiVersion = "1.16"
    name = "GrapplingHook"
    commands {
        register("grapplinghook") {
            description = "Shows plugin help."
            aliases = listOf("gh")
        }
    }
}